use crowd_trace::{
    AgentRecord, Header, TraceError, FLAG_ARRIVED, FORMAT_VERSION, HEADER_BYTES, RECORD_BYTES,
};

#[test]
fn header_round_trips() {
    let h = Header {
        tick_count: 1234,
        agent_count: 1000,
        ticks_per_second: 30,
        world_to_meter: 1.0,
    };
    let bytes = h.encode();
    assert_eq!(bytes.len(), HEADER_BYTES);
    let back = Header::decode(&bytes).expect("decode");
    assert_eq!(back.tick_count, 1234);
    assert_eq!(back.agent_count, 1000);
    assert_eq!(back.ticks_per_second, 30);
    assert_eq!(back.world_to_meter, 1.0);
}

#[test]
fn header_rejects_bad_magic() {
    let mut bytes = Header {
        tick_count: 1,
        agent_count: 1,
        ticks_per_second: 30,
        world_to_meter: 1.0,
    }
    .encode();
    bytes[0] = b'X';
    assert!(matches!(Header::decode(&bytes), Err(TraceError::BadMagic)));
}

#[test]
fn header_rejects_future_version() {
    let mut bytes = Header {
        tick_count: 1,
        agent_count: 1,
        ticks_per_second: 30,
        world_to_meter: 1.0,
    }
    .encode();
    bytes[8..12].copy_from_slice(&(FORMAT_VERSION + 1).to_le_bytes());
    match Header::decode(&bytes) {
        Err(TraceError::UnsupportedVersion { found, expected }) => {
            assert_eq!(found, FORMAT_VERSION + 1);
            assert_eq!(expected, FORMAT_VERSION);
        }
        other => panic!("expected UnsupportedVersion, got {other:?}"),
    }
}

#[test]
fn header_rejects_short_buffer() {
    let bytes = [0u8; 4];
    assert!(matches!(
        Header::decode(&bytes),
        Err(TraceError::Truncated { .. })
    ));
}

// `encode` and `decode` share the same offset constants, so a round-trip
// test alone cannot catch a symmetric mistake (e.g. two same-width fields
// swapped in both functions at once). This test pins the on-disk layout
// against a literal byte array computed BY HAND from the documented offsets
// (magic 0..8, version 8..12, tick_count 12..20, agent_count 20..24,
// ticks_per_second 24..28, world_to_meter 28..32) — it must never be
// generated by calling `encode`, or it stops proving anything.
#[test]
fn header_layout_is_pinned_to_the_spec() {
    let h = Header {
        tick_count: 0x0102_0304_0506_0708,
        agent_count: 0x1112_1314,
        ticks_per_second: 30,
        world_to_meter: 1.0, // bits 0x3F800000 -> LE 00 00 80 3F
    };

    #[rustfmt::skip]
    let expected: [u8; 32] = [
        // magic "CRWDTRC0" (0..8)
        0x43, 0x52, 0x57, 0x44, 0x54, 0x52, 0x43, 0x30,
        // version = 0 (8..12)
        0x00, 0x00, 0x00, 0x00,
        // tick_count = 0x0102_0304_0506_0708, LE (12..20)
        0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
        // agent_count = 0x1112_1314, LE (20..24)
        0x14, 0x13, 0x12, 0x11,
        // ticks_per_second = 30, LE (24..28)
        0x1E, 0x00, 0x00, 0x00,
        // world_to_meter = 1.0f32 -> bits 0x3F80_0000, LE (28..32)
        0x00, 0x00, 0x80, 0x3F,
    ];

    assert_eq!(h.encode(), expected);
}

fn sample_record() -> AgentRecord {
    AgentRecord {
        agent_id: 0x0123_4567_89ab_cdef,
        position: [1.5, -2.25],
        orientation: 0.75,
        flags: FLAG_ARRIVED,
        clip_index: 3,
        phase: 0.5,
        playback_rate: 1.25,
        render_tier: 2,
    }
}

#[test]
fn record_is_packed_to_35_bytes() {
    assert_eq!(RECORD_BYTES, 35);
    assert_eq!(sample_record().encode().len(), 35);
}

#[test]
fn record_round_trips() {
    let r = sample_record();
    let back = AgentRecord::decode(&r.encode()).expect("decode");
    assert_eq!(back.agent_id, r.agent_id);
    assert_eq!(back.position, r.position);
    assert_eq!(back.orientation, r.orientation);
    assert_eq!(back.flags, r.flags);
    assert_eq!(back.clip_index, r.clip_index);
    assert_eq!(back.phase, r.phase);
    assert_eq!(back.playback_rate, r.playback_rate);
    assert_eq!(back.render_tier, r.render_tier);
}

#[test]
fn record_preserves_full_64_bit_id() {
    // Stable identity is a contract guarantee. A truncated ID is not a
    // stable ID, so the high word must survive a round trip intact.
    let mut r = sample_record();
    r.agent_id = u64::MAX - 1;
    let back = AgentRecord::decode(&r.encode()).expect("decode");
    assert_eq!(back.agent_id, u64::MAX - 1);
}

#[test]
fn record_rejects_short_buffer() {
    let bytes = [0u8; RECORD_BYTES - 1];
    assert!(AgentRecord::decode(&bytes).is_err());
}

// Same rationale as `header_layout_is_pinned_to_the_spec`: pin the record
// layout to a literal byte array computed BY HAND from the brief's
// documented offsets (agent_id 0..8, position[0] 8..12, position[1] 12..16,
// orientation 16..20, flags 20..24, clip_index 24..26, phase 26..30,
// playback_rate 30..34, render_tier 34) so a symmetric offset swap inside
// both `encode` and `decode` cannot pass silently.
#[test]
fn record_layout_is_pinned_to_the_spec() {
    let r = AgentRecord {
        agent_id: 0x0807_0605_0403_0201,
        position: [1.5, -2.25], // bits 0x3FC00000, 0xC0100000
        orientation: 0.75,      // bits 0x3F400000
        flags: FLAG_ARRIVED,    // 1 << 1 = 2
        clip_index: 3,
        phase: 0.5,          // bits 0x3F000000
        playback_rate: 1.25, // bits 0x3FA00000
        render_tier: 2,
    };

    #[rustfmt::skip]
    let expected: [u8; 35] = [
        // agent_id = 0x0807_0605_0403_0201, LE (0..8)
        0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08,
        // position[0] = 1.5f32 -> bits 0x3FC0_0000, LE (8..12)
        0x00, 0x00, 0xC0, 0x3F,
        // position[1] = -2.25f32 -> bits 0xC010_0000, LE (12..16)
        0x00, 0x00, 0x10, 0xC0,
        // orientation = 0.75f32 -> bits 0x3F40_0000, LE (16..20)
        0x00, 0x00, 0x40, 0x3F,
        // flags = FLAG_ARRIVED = 2, LE (20..24)
        0x02, 0x00, 0x00, 0x00,
        // clip_index = 3, LE (24..26)
        0x03, 0x00,
        // phase = 0.5f32 -> bits 0x3F00_0000, LE (26..30)
        0x00, 0x00, 0x00, 0x3F,
        // playback_rate = 1.25f32 -> bits 0x3FA0_0000, LE (30..34)
        0x00, 0x00, 0xA0, 0x3F,
        // render_tier = 2 (34)
        0x02,
    ];

    assert_eq!(r.encode(), expected);
}
