[package]
name = "crowd-core"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
blake3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
crowd-cache = { path = "../crowd-cache" }
jsonschema = { version = "0.33", default-features = false }
proptest = { workspace = true }
tempfile = "3.20"
