"""Render a baked crowd trace to image frames from inside Blender.

Runs headless via `--python`. This is a media tool, not a test: it exists so
the recording checked in under `docs/media/` can be regenerated by anyone
with the trace and Blender, rather than being an unreproducible screen
capture of somebody's desktop.

Playback itself goes through the shipped extension -- `TracePlayback` reads
the trace and `geometry_nodes.attach()` instances the agents -- so what gets
recorded is the real pipeline, not a bespoke visualisation. Everything this
module adds on top (ground plane, camera, per-stream materials) is presentation
for the recording only and never touches agent state.

Timings printed here are NOT performance measurements. Rendering dominates,
and each frame is rendered after a sync rather than as part of a timed
playback loop. Quote `scripts/blender-playback-test.sh` for playback cost.

Environment:
    CROWD_TRACE_PATH  trace to render (required)
    CROWD_FRAME_DIR   directory for frame-%05d.png (required)
    CROWD_TICK_STEP   render every Nth tick (default 20)
    CROWD_RES_X       horizontal resolution (default 960)
"""

import os
import sys
import time

import numpy as np

import addon_utils
import bpy
import mathutils

EXTENSION = "bl_ext.user_default.blender_crowd"

# Scene extents are NOT hardcoded. Scene geometry scales with the population
# (see `population_scale` in crowd-core's scenes.rs: lengths grow with the
# square root of the agent count, so a 1,000-agent crossing is ~3.2x the
# nominal 40x40 arena). Framing is therefore measured from the trace itself.
FRAMING_MARGIN = 1.15

# Camera tilt, as the ratio of horizontal to vertical offset from the centre
# of the crowd. Chosen so a square arena's foreshortened height just fills a
# 16:9 frame: any steeper and the arena is cropped top and bottom, any
# shallower and the frame wastes rows on empty background, which at GIF
# sizes costs agent pixels that are already scarce.
CAMERA_TILT_RATIO = 1.23

# The shipped node group instances a cone of depth 1.7 centred on the agent
# point, so half of it sits below z=0. Drop the ground by that half-depth and
# the agents stand on it instead of wading through it.
CONE_HALF_DEPTH = 0.85

COLOUR_BACKGROUND = (0.045, 0.05, 0.07, 1.0)
COLOUR_GROUND = (0.10, 0.11, 0.14, 1.0)
COLOUR_EASTBOUND = (0.95, 0.45, 0.15, 1.0)
COLOUR_NORTHBOUND = (0.20, 0.70, 0.95, 1.0)


def clear_scene():
    """Empty the startup file, which otherwise contributes a cube and a lamp."""
    bpy.ops.object.select_all(action="SELECT")
    bpy.ops.object.delete(use_global=False)


def scan_trace(playback, data):
    """Walk the whole trace once for stream labels and framing bounds.

    Two things have to come from the data rather than from constants:

    Stream label. The trace carries no destination channel, so it is
    recovered by watching each slot until it first holds a real agent
    (flags != 0, the discriminant the trace format defines for an occupied
    slot) and recording where that agent stood. Agents spawn on a stagger,
    so this needs a scan rather than a single read of tick 0. The west strip
    starts at low x and high y and the south strip at high x and low y, so
    `x < y` separates them without depending on the scene's scale.

    Framing bounds. Agents leave the spawn strips and jam wherever they jam,
    so the camera is fitted to the positions actually occupied.

    Returns (stream, minimum, maximum) over the live agents.
    """
    count = playback.agent_count
    stream = np.full(count, -1, dtype=np.int32)
    flags = np.empty(count, dtype=np.int32)
    positions = np.empty(count * 3, dtype=np.float32)
    minimum = np.array([np.inf, np.inf], dtype=np.float64)
    maximum = np.array([-np.inf, -np.inf], dtype=np.float64)

    for tick in range(playback.tick_count):
        playback.sync_to_tick(tick)
        data.attributes["flags"].data.foreach_get("value", flags)
        data.attributes["position"].data.foreach_get("vector", positions)
        live = flags != 0
        if not np.any(live):
            continue

        xy = positions.reshape(count, 3)[:, :2]
        live_xy = xy[live]
        minimum = np.minimum(minimum, live_xy.min(axis=0))
        maximum = np.maximum(maximum, live_xy.max(axis=0))

        newly_spawned = live & (stream < 0)
        if np.any(newly_spawned):
            spawned_xy = xy[newly_spawned]
            stream[newly_spawned] = np.where(
                spawned_xy[:, 0] < spawned_xy[:, 1], 0, 1
            )

    if np.any(stream < 0):
        # Not fatal for a recording: a slot that never holds an agent never
        # renders, because the shipped node group hides flags == 0 slots.
        print("warning: {} slots never spawned".format(int(np.sum(stream < 0))))
        stream[stream < 0] = 0
    return stream, minimum, maximum


def make_material(name, colour):
    material = bpy.data.materials.new(name)
    material.use_nodes = False
    # Workbench's MATERIAL colour mode reads diffuse_color, not a node tree.
    material.diffuse_color = colour
    return material


def build_colour_group(mat_east, mat_north):
    """Realize the instances and colour them by their stream label.

    Kept as a second modifier so the shipped `CrowdInstances` group stays
    exactly as it ships: this reads the `stream` attribute that instancing
    propagated and does nothing but assign a material.
    """
    group = bpy.data.node_groups.new("CrowdRecordingColour", "GeometryNodeTree")
    group.interface.new_socket(
        "Geometry", in_out="INPUT", socket_type="NodeSocketGeometry"
    )
    group.interface.new_socket(
        "Geometry", in_out="OUTPUT", socket_type="NodeSocketGeometry"
    )
    nodes, links = group.nodes, group.links

    group_in = nodes.new("NodeGroupInput")
    group_in.location = (-600, 0)
    group_out = nodes.new("NodeGroupOutput")
    group_out.location = (600, 0)

    realize = nodes.new("GeometryNodeRealizeInstances")
    realize.location = (-400, 0)

    stream_attr = nodes.new("GeometryNodeInputNamedAttribute")
    stream_attr.location = (-400, 250)
    stream_attr.data_type = "INT"
    stream_attr.inputs["Name"].default_value = "stream"

    is_north = nodes.new("FunctionNodeCompare")
    is_north.location = (-200, 250)
    is_north.data_type = "INT"
    is_north.operation = "EQUAL"
    is_north.inputs["B"].default_value = 1

    set_east = nodes.new("GeometryNodeSetMaterial")
    set_east.location = (-100, 0)
    set_east.inputs["Material"].default_value = mat_east

    set_north = nodes.new("GeometryNodeSetMaterial")
    set_north.location = (150, 0)
    set_north.inputs["Material"].default_value = mat_north

    links.new(group_in.outputs[0], realize.inputs[0])
    links.new(realize.outputs[0], set_east.inputs["Geometry"])
    links.new(set_east.outputs["Geometry"], set_north.inputs["Geometry"])
    links.new(stream_attr.outputs["Attribute"], is_north.inputs["A"])
    links.new(is_north.outputs["Result"], set_north.inputs["Selection"])
    links.new(set_north.outputs["Geometry"], group_out.inputs[0])
    return group


def build_ground(centre, extent):
    bpy.ops.mesh.primitive_plane_add(
        size=extent,
        location=(centre[0], centre[1], -CONE_HALF_DEPTH),
    )
    ground = bpy.context.active_object
    ground.name = "ground"
    ground.data.materials.append(make_material("ground", COLOUR_GROUND))
    return ground


def build_camera(centre, extent):
    """An orthographic three-quarter view fitted to the occupied area.

    Orthographic on purpose: the interesting content is the shape of the two
    flows and where they jam, and perspective would make agents at the far
    corner smaller than identical agents at the near one.
    """
    camera_data = bpy.data.cameras.new("camera")
    camera_data.type = "ORTHO"
    camera_data.ortho_scale = extent * FRAMING_MARGIN
    camera = bpy.data.objects.new("camera", camera_data)
    bpy.context.scene.collection.objects.link(camera)

    # Tilted back from straight overhead far enough to read as a 3D shot,
    # but still steep enough that the far side of the crowd is not hidden
    # behind the near side.
    height = extent * 0.8
    camera.location = (
        centre[0],
        centre[1] - height * CAMERA_TILT_RATIO,
        height,
    )
    target = mathutils.Vector((centre[0], centre[1], 0.0))
    direction = target - camera.location
    camera.rotation_euler = direction.to_track_quat("-Z", "Y").to_euler()
    bpy.context.scene.camera = camera
    return camera


def configure_render(scene, res_x):
    scene.render.engine = "BLENDER_WORKBENCH"
    scene.render.resolution_x = res_x
    scene.render.resolution_y = int(res_x * 9 / 16)
    scene.render.resolution_percentage = 100
    scene.render.image_settings.file_format = "PNG"
    scene.render.film_transparent = False

    shading = scene.display.shading
    # Flat shading keeps each agent a single solid colour. That is both the
    # clearest read at this scale and what keeps the GIF palette tiny: a lit
    # shading mode would spray thousands of near-identical ramp colours that
    # GIF cannot compress and that add nothing here.
    shading.light = "FLAT"
    shading.color_type = "MATERIAL"
    shading.show_object_outline = True
    shading.object_outline_color = (0.02, 0.02, 0.03)
    shading.show_specular_highlight = False

    scene.world = bpy.data.worlds.new("recording")
    scene.world.use_nodes = False
    scene.world.color = COLOUR_BACKGROUND[:3]
    scene.render.dither_intensity = 0.0


def main():
    trace_path = os.environ["CROWD_TRACE_PATH"]
    frame_dir = os.environ["CROWD_FRAME_DIR"]
    tick_step = int(os.environ.get("CROWD_TICK_STEP", "20"))
    res_x = int(os.environ.get("CROWD_RES_X", "960"))

    os.makedirs(frame_dir, exist_ok=True)
    clear_scene()

    addon_utils.enable(EXTENSION, default_set=True)
    from bl_ext.user_default.blender_crowd.trace_playback import TracePlayback
    from bl_ext.user_default.blender_crowd import geometry_nodes

    playback = TracePlayback(trace_path)
    obj = playback.object
    data = obj.data
    print("agents: {}".format(playback.agent_count))
    print("ticks: {}".format(playback.tick_count))

    stream, minimum, maximum = scan_trace(playback, data)
    print(
        "streams: {} eastbound, {} northbound".format(
            int(np.sum(stream == 0)), int(np.sum(stream == 1))
        )
    )
    centre = (minimum + maximum) / 2.0
    extent = float(np.max(maximum - minimum))
    print(
        "occupied area: {:.1f} x {:.1f} centred on ({:.1f}, {:.1f})".format(
            maximum[0] - minimum[0], maximum[1] - minimum[1], centre[0], centre[1]
        )
    )
    if "stream" not in data.attributes:
        data.attributes.new("stream", "INT", "POINT")
    data.attributes["stream"].data.foreach_set("value", stream)
    data.update_tag()

    geometry_nodes.attach(obj)
    colour_modifier = obj.modifiers.new("CrowdRecordingColour", "NODES")
    colour_modifier.node_group = build_colour_group(
        make_material("eastbound", COLOUR_EASTBOUND),
        make_material("northbound", COLOUR_NORTHBOUND),
    )

    build_ground(centre, extent)
    build_camera(centre, extent)
    scene = bpy.context.scene
    configure_render(scene, res_x)

    ticks = range(0, playback.tick_count, tick_step)
    total = len(ticks)
    print("rendering {} frames (every {} ticks)".format(total, tick_step))

    start = time.perf_counter()
    for index, tick in enumerate(ticks):
        playback.sync_to_tick(tick)
        scene.render.filepath = os.path.join(frame_dir, "frame-{:05d}".format(index))
        bpy.ops.render.render(write_still=True)
        if index % 25 == 0 or index == total - 1:
            print(
                "  frame {}/{} (tick {})".format(index + 1, total, tick),
                flush=True,
            )
    elapsed = time.perf_counter() - start

    # Render wall time, not a playback measurement. Stated explicitly so this
    # number never gets mistaken for the 0.0285 ms/tick playback figure.
    print("frames: {}".format(total))
    print("render_wall_s: {:.1f} (rendering, NOT a playback measurement)".format(elapsed))
    print("PASS: rendered {} frames to {}".format(total, frame_dir))


main()
